name: Test application

on:
  workflow_dispatch:
    inputs:
      TEST_TYPE:
        required: false
        type: string
        default: cucumber
        description: Either 'unit' or 'cucumber' or 'cypress'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
        working-directory: ./src/app
      - run: cypress run --env username=${{secrets.CYPRESS_USERNAME}},password=${{secrets.CYPRESS_PASSWORD}}
        working-directory: ./src/app